version: '3.7'

services: 
    webp:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn StayHome.wsgi:application --bind 0.0.0.0:8000
        container_name: webprod
        volumes: 
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/mediafiles
        expose:
            - 8000
        env_file: 
            - ./.env.prod
        depends_on: 
            - db
    db:
        image: postgres:12.2-alpine
        container_name: dbprod
        volumes: 
            - postgres_data:/var/lib/postgresql/data
        env_file: 
            - ./.env.prod.db
    nginx:
        build: ./nginx
        volumes: 
            - static_volume:/home/app/web/static
            - media_volume:/home/app/web/mediafiles
            - ./nginx/data/log:/var/log/nginx
            - ./nginx/data/certbot/conf:/etc/letsencrypt
            - ./nginx/data/certbot/www:/var/www/certbot
        ports: 
            - 80:80
            - 443:443
        depends_on: 
            - webp
    certbot:
        image: certbot/certbot
        volumes:
            - ./nginx/data/certbot/conf:/etc/letsencrypt
            - ./nginx/data/certbot/www:/var/www/certbot
volumes: 
    postgres_data:
    static_volume:
    media_volume: