# Generated by Django 3.0.5 on 2020-04-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordwolves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='num_majors',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='room',
            name='num_players',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='room',
            name='pub_date',
            field=models.DateTimeField(verbose_name='created_at'),
        ),
    ]
