# Generated by Django 3.0.5 on 2020-04-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordwolves', '0002_auto_20200414_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vote',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
